### ISSUE TITLE
Fix error in tests

### ISSUE THREAD

**Issue by maximalism2** [necinc/mstr#4]
```
  Model interface
  1) Uncaught error outside test suite
  2) Uncaught error outside test suite
    Price
      .create(), must returns an object with error when:
  ✓ passed nothing
  ✓ passed not object
  ✓ passed {} (empty object)
  ✓ passed instance without name property
  ✓ passed instance when the name property is not a string
  ✓ passed instance with the name property which is an empty string
  ✓ passed instance with the name property which is longer than 200 characters
      .readById(), must returns an object with error when:
  ✓ passed any arguments
  ✓ passed some id, but it is not a string
  ✓ passed an empty id string
      .update(), must returns an object with error when:
  ✓ passed any arguments
  ✓ passed only one argument
  ✓ passed arguments, where the first argument (id) is not a string
  ✓ passed arguments. where id is an empty string
  ✓ passed arguments, where the second argument (query) is not an object
  ✓ passed arguments, where query is an empty object
  ✓ passed arguments, where query hasn't one of required fields
  ✓ passed query, where name exists, but it is not a string
  ✓ passed query. where name exists, but it is an empty string
  ✓ passed query, where name exists, but it is bigger than 200 characters
  ✓ passed query, where discount exists, but it is not a number
  ✓ passed query, where discount exists, but it is not between 0 and 100
  ✓ passed qeury, where products exists, but it is not an array
  ✓ passed query, where products exists, but items is not the stings
      .remove(), must returns an object with error when:
  ✓ passed any arguments
  ✓ passed some id, but it is not a string
  ✓ passed an empty id string
  Test to test
  ✓ test to test
  28 passing (25ms)
  2 failing
  1) Model interface Uncaught error outside test suite:
     Uncaught Error: connect ECONNREFUSED 127.0.0.1:27017
      at Object.exports._errnoException (util.js:893:11)
      at exports._exceptionWithHostPort (util.js:916:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1075:14)
  2) Model interface Uncaught error outside test suite:
     Uncaught Error: connect ECONNREFUSED 127.0.0.1:27017
      at Object.exports._errnoException (util.js:893:11)
      at exports._exceptionWithHostPort (util.js:916:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1075:14)

```

**Comment by maximalism2** [comment]
Fixed!
